version: '3.12'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - Richon1/docker.env
    volumes:
      - .:/srv/app
    ports:
      - '0.0.0.0:3500:3500'
    command: python manage.py runserver 0.0.0.0:3500

volumes:
  static-data:


